/* 
 This file was generated by Dashcode.  
 You may edit this file to customize your widget or web page 
 according to the license.txt file included in the project.
 */

//
// Function: load()
// Called by HTML body element's onload event when the web application is ready to start
//
function load()
{
    var pusher = new Pusher('7f47b26baff3b03526e2');
    var channel = pusher.subscribe('Chat');
	var indicatorToChange = document.getElementById("div");
    channel.bind('statuslight', function(data) {
      indicatorToChange.object.setValue(data);
    });

	dashcode.setupParts();
}
